### ISSUE TITLE
hard to start

### ISSUE THREAD

**Issue by mibamur** [rubychan/shootout#3]
```
SHOOTERS=all ruby shootout.rb

                       Welcome to
  ~~~ The Great Syntax Highlighter Shootout v1.7 ~~~

using Ruby 2.3.1 and Python 2.7.11, repeating 5 times

                  CodeRay 1.1.1       coderay 1.1.1         Rouge 2.0.2       rougify 2.0.2        Albino 1.3.3   Pygments.rb 0.6.3    pygmentize 2.1.3      highlight 3.27
C (218 kB)
=> terminal           2199 kB/s            969 kB/s/Users/user/.rvm/gems/ruby-2.3.1@rails5/gems/rouge-2.0.2/lib/rouge.rb:24:in `highlight': unknown formatter  (RuntimeError)
    from /Users/user/Documents/mibamur/shootout/adapters/rouge.rb:12:in `highlight'
    from /Users/user/Documents/mibamur/shootout/shootout_adapter.rb:33:in `benchmark'
    from shootout.rb:86:in `block (4 levels) in <main>'
    from shootout.rb:85:in `each'
    from shootout.rb:85:in `block (3 levels) in <main>'
    from shootout.rb:80:in `each'
    from shootout.rb:80:in `block (2 levels) in <main>'
    from shootout.rb:48:in `each'
    from shootout.rb:48:in `block in <main>'
    from shootout.rb:30:in `each'
    from shootout.rb:30:in `<main>'
```

**Comment by mibamur** [comment]
```
rake

                       Welcome to
  ~~~ The Great Syntax Highlighter Shootout v1.7 ~~~

using Ruby 2.3.1 and Python 2.7.11, repeating 5 times

                  CodeRay 1.1.1         Rouge 2.0.2   Pygments.rb 0.6.3
C (218 kB)
=> terminal           2167 kB/s/Users/user/.rvm/gems/ruby-2.3.1@rails5/gems/rouge-2.0.2/lib/rouge.rb:24:in `highlight': unknown formatter  (RuntimeError)
	from /Users/user/Documents/mibamur/shootout/adapters/rouge.rb:12:in `highlight'
	from /Users/user/Documents/mibamur/shootout/shootout_adapter.rb:33:in `benchmark'
	from ./shootout.rb:86:in `block (4 levels) in <main>'
	from ./shootout.rb:85:in `each'
	from ./shootout.rb:85:in `block (3 levels) in <main>'
	from ./shootout.rb:80:in `each'
	from ./shootout.rb:80:in `block (2 levels) in <main>'
	from ./shootout.rb:48:in `each'
	from ./shootout.rb:48:in `block in <main>'
	from ./shootout.rb:30:in `each'
	from ./shootout.rb:30:in `<main>'
```

**Comment by korny** [comment]
Is this still occurring for you?
